version: "3"
volumes:
  home:
services:
  dev:
    build:
      context: "https://github.com/sebfisch/docker-java-dev.git#latest"
      # Adjust the build args to reflect your local setup
      args:
        JAVA_VERSION: 11
        # UID: 501
        # GID: 501
    hostname: java-dev
    command: tmux -u new -s java-concurrency-code
    environment:
      # Adjust to reflect your own timezone
      - TZ=Europe/Berlin
      # Adjust to reflect your own X server
      - DISPLAY=docker.for.win.localhost:0.0
        # The following line disables class data sharing for the JVM
        # which leads to a warning message on some architectures.
        # - JAVA_OPTIONS=-Xshare:off
    volumes:
      - home:/home
      - ~/.ssh:/home/me/.ssh/:ro
      - .:/home/me/java-concurrency-code
    working_dir: /home/me/java-concurrency-code
    deploy:
      resources:
        limits:
          cpus: 12
          memory: 8G
